backend:
  name: github-api #netlify-api
  repo: dorelljames/business-static-template
  branch: master
  endpoint: https://webriq-portal.dev/api/
  #url: http://localhost:8080

production:
  backend:
    name: github-api
    repo: dorelljames/spike-collections-records-template # Path to your Github repository
    branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go
public_folder: "assets"

responsive_images: true

collections: # A list of collections the CMS should be able to edit
  - name: "sitedata"
    label: "Site Information"
    create: false
    files:
      - name: "sitedata"
        label: "Site Information"
        file: "data/site.json"
        description: "edit site setting"
        fields:
          - label: "Site Information"
            name: "sitedata"
            widget: "list"
            fields:
              - {label: "Favicon", name: "icon", widget: "image", media_folder: "assets/img"}
              - {label: "Site Logo", name: "logo", widget: "image", media_folder: "assets/img"}
              - {label: "Site name", name: "sitename", widget: "string"}
              - {label: "Website Description", name: "metadesc", widget: "string"}
              - {label: "Author", name: "metauthor", widget: "string"}
              - {label: "Keywords", name: "metakeyword", widget: "string"}
              - {label: "Footer", name: "footer", widget: "markdown"}
              - {label: "Google Analytics", name: "analytics", widget: "markdown"}

